# Site settings
title: Helena Say
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/freelancer-theme"

# Build settings
markdown: kramdown
permalink: pretty

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: F6F6F6 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  third: fcd670
  third-rgb: "252,214,112"
